package ca.cn.ems.hptaauditconfiguration;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UnlimitedZoneData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("startMilePoint")
	private Double startMilePoint;
	@org.kie.api.definition.type.Label("endMilePoint")
	private Double endMilePoint;
	@org.kie.api.definition.type.Label("startBuffer")
	private Double startBuffer;
	@org.kie.api.definition.type.Label("endBuffer")
	private Double endBuffer;
	@org.kie.api.definition.type.Label("direction")
	private java.lang.String direction;

	@org.kie.api.definition.type.Label("startMilePointWithBuffer")
	private Double startMilePointWithBuffer;

	@org.kie.api.definition.type.Label("endMilePointWithBuffer")
	private Double endMilePointWithBuffer;

	@org.kie.api.definition.type.Label(value = "restrictionType")
	private java.lang.String restrictionType;

	public UnlimitedZoneData() {
	}

	public java.lang.String getDirection() {
		return this.direction;
	}

	public void setDirection(java.lang.String direction) {
		this.direction = direction;
	}

	public java.lang.Double getStartMilePoint() {
		return this.startMilePoint;
	}

	public void setStartMilePoint(java.lang.Double startMilePoint) {
		this.startMilePoint = startMilePoint;
	}

	public java.lang.Double getEndMilePoint() {
		return this.endMilePoint;
	}

	public void setEndMilePoint(java.lang.Double endMilePoint) {
		this.endMilePoint = endMilePoint;
	}

	public java.lang.Double getStartBuffer() {
		return this.startBuffer;
	}

	public void setStartBuffer(java.lang.Double startBuffer) {
		this.startBuffer = startBuffer;
	}

	public java.lang.Double getEndBuffer() {
		return this.endBuffer;
	}

	public void setEndBuffer(java.lang.Double endBuffer) {
		this.endBuffer = endBuffer;
	}

	public java.lang.Double getStartMilePointWithBuffer() {
		return this.startMilePointWithBuffer;
	}

	public void setStartMilePointWithBuffer(
			java.lang.Double startMilePointWithBuffer) {
		this.startMilePointWithBuffer = startMilePointWithBuffer;
	}

	public java.lang.Double getEndMilePointWithBuffer() {
		return this.endMilePointWithBuffer;
	}

	public void setEndMilePointWithBuffer(
			java.lang.Double endMilePointWithBuffer) {
		this.endMilePointWithBuffer = endMilePointWithBuffer;
	}

	public java.lang.String getRestrictionType() {
		return this.restrictionType;
	}

	public void setRestrictionType(java.lang.String restrictionType) {
		this.restrictionType = restrictionType;
	}

	public UnlimitedZoneData(java.lang.Double startMilePoint,
			java.lang.Double endMilePoint, java.lang.Double startBuffer,
			java.lang.Double endBuffer, java.lang.String direction,
			java.lang.Double startMilePointWithBuffer,
			java.lang.Double endMilePointWithBuffer,
			java.lang.String restrictionType) {
		this.startMilePoint = startMilePoint;
		this.endMilePoint = endMilePoint;
		this.startBuffer = startBuffer;
		this.endBuffer = endBuffer;
		this.direction = direction;
		this.startMilePointWithBuffer = startMilePointWithBuffer;
		this.endMilePointWithBuffer = endMilePointWithBuffer;
		this.restrictionType = restrictionType;
	}

}